### PR TITLE
Updated modal to show on first click.

### LINKED ISSUE #8: Modal does not appear on first click.
When clicking the "More Info" button in the completed project, the `div.modal` does not appear.  This happens in Edge (Chrome), Chrome, and Firefox.  A second click on "More Info" shows the box.

### PR DESCRIPTION
**Pull request by exegeteio**
Not sure if it makes sense for the Github code to diverge from the Youtube code, but I got stuck on this bug for a bit.  The fix may be a bit beyond a 101 level.

When clicking "More Info" for the first time, the modal does not yet exist in the DOM (`selectedProduct == null`).   Thus, Bootstrap.js could not toggle the `show` class on the modal.  Once the modal existed (after `selectedProduct` was not `null`), Bootstrap.js could find the modal and show it.

Moving the `@if` inside the modal (so that `#productModal` always exists) allows Bootstrap.js to find the modal and act accordingly on the first click, while Blazor updates the modal contents.

Fixes #8

### CODE REVIEW

**Comment by waseemtahir01** [comment]
Hi, 
same here on first click modal doesn't appear, as per your solution if @if moves inside the modal it will appear on the first click, but not closing automatically. 

2nd issue, after deploying an application on azure, (http://contoscraft.azurewebsites.net/) after submitting the rating, an error will display after refreshing the website, moreover Rating not updating as it appearing on localhost.

**Comment by msoliman0512** [comment]
This solution didn't work with me as well, I still get nothing when I press show more button either using chrome or firefox

**Comment by sabuncu** [comment]
@exegete46 Thank you!  Your fix works.

**Comment by sabuncu** [comment]
Just curious why this PR has not been merged.  It does fix the first-click issue for the modal.  Thanks.
I am tagging @jamesmontemagno because he's merged the only other PR for this repo.
CC: @exegete46

**Comment by jamesmontemagno** [comment]
@jongalloway any reason not to merge?

**Pull request merged**
